theme: jekyll-theme-slate
title: Welcome to Jonathan's Homepage
description: Hi my name is Jonathan Davidson, and I study mathematics. Here you will find a repository of my work on various unsolved math problems. Each problem includes a statement of the problem, historical context, progress made by other mathematicians, and my own heuristics and attempts. 
